args:
  - -e
resources:
  requests:
    cpu: 200m
    memory: 192Mi
autoscaling: 
  enabled: false
  keda: true   
podAnnotations:
  reloader.stakater.com/auto: "true"
secret:
  host: 
  #must be org or system token requires 1.98>
  token: 
config:
  syslogng:
    # template assumes all destinations are in use remove 
    # both filter and logpath references for unused features filters may remain
    
    filters:
      - name: f_azure
        condition: |-
          tags('vendor:microsoft') and tags('product:azure');
      - name: f_azuread
        condition: |-
          tags('vendor:microsoft') and tags('product:azuread');
      - name: f_defender
        condition: |-
          tags('vendor:microsoft') and tags('product:defender');
      - name: f_intune
        condition: |-
          tags('vendor:microsoft') and tags('product:intune');
    logPaths:
      - name: azure
        filters:
          - filter(f_azure)
        flags: [catchall, final]
        template: t_logscale_parsed
        tags: 
          - name: vendor
            value: microsoft
        repo: segway-iaas-microsoft-azure
        sourcetype: azure
      - name: azuread
        filters:
          - filter(f_azuread)
        flags: [catchall, final]
        template: t_logscale_parsed
        tags: 
          - name: vendor
            value: microsoft
        sourcetype: azuread
        repo: segway-saas-microsoft-azuread
      - name: defender
        filters:
          - filter(f_defender)
        flags: [catchall, final]
        template: t_logscale_parsed
        tags: 
          - name: vendor
            value: microsoft
        sourcetype: defender
        repo: segway-saas-microsoft-azuread
      - name: intune
        filters:
          - filter(f_azuread)
        flags: [catchall, final]
        template: t_logscale_parsed
        tags: 
          - name: vendor
            value: microsoft
        sourcetype: intune
        repo: segway-saas-microsoft-intune
      - name: fallback
        template: t_logscale_parsed
        sourcetype: segway-unknown
        repo: app-segway-fallback
        flags: [catchall, fallback, final]
