args:
  - -det
podAnnotations:
  reloader.stakater.com/auto: "true"
secret:
  url: "https://"
config:
  syslogng:
    repos:
      - name: iaas-microsoft-azure
        token: 
      - name: saas-microsoft-azuread
        token: 
      - name: saas-microsoft-defender
        token: 
      - name: saas-microsoft-intune
        token: 
      - name: app-segway-fallback
        token: 
        isCatchAll: true
    filters:
      - name: f_azure
        condition: |-
          tags('vendor:microsoft') and tags('product:azure');
      - name: f_azuread
        condition: |-
          tags('vendor:microsoft') and tags('product:azuread');
      - name: f_defender
        condition: |-
          tags('vendor:microsoft') and tags('product:defender');
      - name: f_intune
        condition: |-
          tags('vendor:microsoft') and tags('product:intune');
    logPaths:
      - name: azure
        filters:
          - filter(f_azure)
        destinations:
          - iaas-microsoft-azure
        flags: [catchall, final]
        template: t_logscale_parsed
        tags: 
          - name: vendor
            value: microsoft
          - name: type
            value: azure
      - name: azuread
        filters:
          - filter(f_azuread)
        destinations:
          - saas-microsoft-azuread
        flags: [catchall, final]
        template: t_logscale_parsed
        tags: 
          - name: vendor
            value: microsoft
          - name: type
            value: azuread
      - name: defender
        filters:
          - filter(f_defender)
        destinations:
          - saas-microsoft-defender
        flags: [catchall, final]
        template: t_logscale_parsed
        tags: 
          - name: vendor
            value: microsoft
          - name: type
            value: defender
      - name: intune
        filters:
          - filter(f_azuread)
        destinations:
          - saas-microsoft-intune
        flags: [catchall, final]
        template: t_logscale_parsed
        tags: 
          - name: vendor
            value: microsoft
          - name: type
            value: intune
      - name: fallback
        destinations:
          - app-segway-fallback
        template: t_logscale_parsed
        flags: [catchall, fallback, final]
