args:
  - -e
resources:
  requests:
    cpu: 200m
    memory: 192Mi
autoscaling:
  enabled: false
  keda: true
podAnnotations:
  reloader.stakater.com/auto: "true"
secret:
  host:
  #must be org or system token requires 1.98>
  token:
config:
  # Uncomment and complete
  # mkdir deployments/prod/global/segway/sources/mimecast || true
  # either use * for all types or review the types and copy desired options
  # cp -r /Users/rfaircloth/Documents/GitHub/hosting-azure-aks/_modules/global/segway/mimecast/<pick type> deployments/prod/global/segway/sources/mimecast/
  # mimecast:
  #   client_id:
  #   secret_id:
  #   host:  api.services.mimecast.com
  syslogng:
    # template assumes all destinations are in use remove
    # both filter and logpath references for unused features filters may remain

    filters:
      - name: f_azure
        condition: |-
          tags('vendor:microsoft') and tags('product:azure');
      - name: f_azuread
        condition: |-
          tags('vendor:microsoft') and tags('product:azuread');
      - name: f_defender
        condition: |-
          tags('vendor:microsoft') and tags('product:defender');
      - name: f_intune
        condition: |-
          tags('vendor:microsoft') and tags('product:intune');
    logPaths:
      - name: azure
        filters:
          - filter(f_azure)
        flags: [catchall, final]
        template: t_logscale_parsed
        tags:
          - name: vendor
            value: microsoft
        repo: iaas-microsoft-azure
        sourcetype: azure
      - name: azuread
        filters:
          - filter(f_azuread)
        flags: [catchall, final]
        template: t_logscale_parsed
        tags:
          - name: vendor
            value: microsoft
        sourcetype: azuread
        repo: saas-microsoft-azuread
      - name: defender
        filters:
          - filter(f_defender)
        flags: [catchall, final]
        template: t_logscale_parsed
        tags:
          - name: vendor
            value: microsoft
        sourcetype: defender
        repo: saas-microsoft-defender
      - name: intune
        filters:
          - filter(f_azuread)
        flags: [catchall, final]
        template: t_logscale_parsed
        tags:
          - name: vendor
            value: microsoft
        sourcetype: intune
        repo: saas-microsoft-intune
      - name: fallback
        template: t_logscale_parsed
        sourcetype: segway-unknown
        repo: app-segway-fallback
        flags: [catchall, fallback, final]
