args:
  - -e
resources:
  requests:
    cpu: 200m
    memory: 192Mi
autoscaling: 
  enabled: false
  keda: true   
podAnnotations:
  reloader.stakater.com/auto: "true"
secret:
  # base URL for logscale do not add trailing slash ie https:///something.someting.com
  url: "https://"
config:
  syslogng:
    # template assumes all destinations are in use remove 
    # both filter and logpath references for unused features filters may remain
    repos:
        #name is internal to segway matching repo is not required
      - name: iaas-microsoft-azure
        #ingest token for azure data
        token: 
        #name is internal to segway matching repo is not required
      - name: saas-microsoft-azuread
        #ingest token for azuread data
        token: 
        #name is internal to segway matching repo is not required
      - name: saas-microsoft-defender
        #ingest token for defender data
        token: 
        #name is internal to segway matching repo is not required
      - name: saas-microsoft-intune
        #ingest token for intune
        token: 
        #name is internal to segway matching repo is not required
      - name: app-segway-fallback
        token: 
        isCatchAll: true
    filters:
      - name: f_azure
        condition: |-
          tags('vendor:microsoft') and tags('product:azure');
      - name: f_azuread
        condition: |-
          tags('vendor:microsoft') and tags('product:azuread');
      - name: f_defender
        condition: |-
          tags('vendor:microsoft') and tags('product:defender');
      - name: f_intune
        condition: |-
          tags('vendor:microsoft') and tags('product:intune');
    logPaths:
      - name: azure
        filters:
          - filter(f_azure)
        destinations:
          - iaas-microsoft-azure
        flags: [catchall, final]
        template: t_logscale_parsed
        tags: 
          - name: vendor
            value: microsoft
          - name: type
            value: azure
      - name: azuread
        filters:
          - filter(f_azuread)
        destinations:
          - saas-microsoft-azuread
        flags: [catchall, final]
        template: t_logscale_parsed
        tags: 
          - name: vendor
            value: microsoft
          - name: type
            value: azuread
      - name: defender
        filters:
          - filter(f_defender)
        destinations:
          - saas-microsoft-defender
        flags: [catchall, final]
        template: t_logscale_parsed
        tags: 
          - name: vendor
            value: microsoft
          - name: type
            value: defender
      - name: intune
        filters:
          - filter(f_azuread)
        destinations:
          - saas-microsoft-intune
        flags: [catchall, final]
        template: t_logscale_parsed
        tags: 
          - name: vendor
            value: microsoft
          - name: type
            value: intune
      - name: fallback
        destinations:
          - app-segway-fallback
        template: t_logscale_parsed
        flags: [catchall, fallback, final]
